name: ps
description: personal site

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  provider: ^6.0.3
  url_launcher: ^6.2.1
  just_audio: ^0.9.36
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/audio/
    - assets/icons/

  fonts:
    - family: retro
      fonts:
        - asset: assets/fonts/retro.ttf
    - family: inter
      fonts:
        - asset: assets/fonts/inter.ttf